displayName=Goals List
author=N1ckoP
description=Simple goals list where it completes automatically when met.
tags=goals,list,goals list,skill,skill list, skill goals, goals, list
plugins=com.goalslist.GoalsListPlugin